Feature/jc 603 create book catalog page
saritasa-nest/camp-js-2024-anastasia-fongrad pull request #1
Opened 2024-07-04 03:18 UTC by fongradnastya

Created html and css for a book catalog page JC-603

2024-07-04 06:03 UTC, timofei-maximov-saritasa requested changes
Please, take a look at `README.md`. We are serving the application using `vite`.

You can run your app using 

```bash
npm run vanilla:serve
```

__Note__: You might have issues with loading your assets. To fix it, you have to co-locate your assets in the same folder with `index.html` file.

![image](https://github.com/saritasa-nest/camp-js-2024-anastasia-fongrad/assets/86595911/c7b5eab8-2381-4350-937b-761709fb33a2)

2024-07-04 07:51 UTC, viktor-sakhno-saritasa requested changes

2024-07-04 07:51 UTC, viktor-sakhno-saritasa commented on apps/vanilla/src/css/base.css
> +}
Be aware, If I don't mistake, form elements like `button`, `input`, `textarea`, etc... will not inherit font-family from `body` or `html` selector. So, you may define font styles here in asterisk, or you could do a `font-family: inherit` for these elements directly.

2024-07-04 07:51 UTC, viktor-sakhno-saritasa commented on apps/vanilla/src/pages/assets/img/icons/chevron-down.svg
Just to let you know, before adding SVG assets, it would be better to optimize it. You can use https://jakearchibald.github.io/svgomg/ service.

2024-07-04 07:51 UTC, viktor-sakhno-saritasa commented on apps/vanilla/src/css/variables.css
Let's group our variables by semantics and meaning, add comments and spaces. Now it’s a little difficult to read this, and then support and search.

2024-07-04 07:51 UTC, viktor-sakhno-saritasa commented on apps/vanilla/src/css/base.css
> +}
Let's move this styles to separate files. Like `heading.css`, and `layout.css`, for example. Because your `base.css` file may increase a lot. For now, it doesn't have a lot of code, but, imagine, if you will start to add styles related to lists, buttons, etc.

2024-07-04 07:51 UTC, viktor-sakhno-saritasa commented on apps/vanilla/src/css/components.css
> +  max-width: var(--space-225);
Are you sure that `--space` variable naming fits to width? Feel free to define another variable with the same value, but with other meaning, if their purposes are different.

2024-07-04 07:51 UTC, viktor-sakhno-saritasa commented on apps/vanilla/src/pages/index.html
> +					</a>
```suggestion
					<a href="/" class="header__link">
						📚 Books app
					</a>
```

2024-07-04 07:51 UTC, viktor-sakhno-saritasa commented on apps/vanilla/src/pages/index.html
> +						<div class="catalog__list">
Let's use `ul` semantic element instead `div`.

2024-07-04 07:51 UTC, viktor-sakhno-saritasa commented on apps/vanilla/src/pages/index.html
> +						<div class="catalog__list">
The same about using `ul`.

2024-07-04 07:51 UTC, viktor-sakhno-saritasa commented on apps/vanilla/src/pages/index.html
> +				<div class="footer__nav">
Your class naming tells me that semantic element `nav` can be used here instead `div`.

2024-07-04 11:40 UTC, irina-baleevskih-saritasa commented on apps/vanilla/src/pages/index.html
> +								<h3 class="book__title">Domain-Driven Design</h3>
I think we shouldn't use <h> tag to book title. We don't have some content below

2024-07-04 11:40 UTC, irina-baleevskih-saritasa commented on apps/vanilla/src/pages/index.html
> +					<div class="aside__filters">
```suggestion
					<div class="aside__filters filters">
```

2024-07-05 10:40 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/css/components.css
> +  grid-template-columns: repeat(5, minmax(0, 1fr));
You can use `auto-fill` delegate column count to grid. 

If you decide to go with `auto-fill` don't forget to add `flex-grow: 1` to `.catalog`

2024-07-05 10:40 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/pages/index.html
> +				<button type="button" class="footer__button-top">
You can implement scroll to to via `a` tag.

`<a href="#">`

2024-07-05 10:40 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/pages/index.html
> +						<h2 class="catalog__heading">1980 year</h2>
Heading is not sticky on mobile.

2024-07-05 10:40 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/css/layout.css
> +}
It's a bit strange that you separated `footer` class and `footer__container`.  

I suggest renaming these class to blocks rather than elements or move these where block is located.

From BEM docs:
> Element
Parts of a block and have no standalone meaning. Any element is semantically tied to its block.

2024-07-05 10:41 UTC, timofei-maximov-saritasa commented
@fongradnastya Don't forget to resolve comments you fixed

2024-07-05 10:50 UTC, fongradnastya commented on apps/vanilla/src/pages/index.html
> +						<h2 class="catalog__heading">1980 year</h2>
I made the filters sticky on mobile devices and tablets. Should I try to stick the headers to the bottom of them?

2024-07-06 23:11 UTC, viktor-sakhno-saritasa requested changes

2024-07-06 23:11 UTC, viktor-sakhno-saritasa commented on apps/vanilla/src/css/components.css
> +  font-family: Inter, sans-serif;
Let's make it a variable.

2024-07-06 23:11 UTC, viktor-sakhno-saritasa commented on apps/vanilla/src/css/components.css
> +  top: -1px; /* To fix visual bag on scrolling */
We usually write a comment at the top of the line to which the comment relates, not from the side.

2024-07-06 23:11 UTC, viktor-sakhno-saritasa commented on apps/vanilla/src/pages/index.html
> +					<ul class="footer__main footer__list">
Semantically, we should use list for elements of the same type. But one element of your list is link and the other is div. I think, list doesn't fit here.

2024-07-06 23:11 UTC, viktor-sakhno-saritasa commented on apps/vanilla/src/pages/index.html
> +							<div class="footer__copyright">
We have good semantic HTML element for such things - https://developer.mozilla.org/en-US/docs/Web/HTML/Element/small

2024-07-08 02:08 UTC, fongradnastya commented on apps/vanilla/src/css/components.css
> +  font-family: Inter, sans-serif;
Stylelint doesn't really allow me to do this, so I had to set the font-family in base.css.

2024-07-08 05:25 UTC, timofei-maximov-saritasa approved these changes
Good job!

2024-07-08 08:34 UTC, viktor-sakhno-saritasa approved these changes

2024-07-08 08:45 UTC, merged