Feature/initialize anime app
saritasa-nest/camp-js-2024-anastasia-fongrad pull request #5
Opened 2024-07-22 04:29 UTC by fongradnastya

Created anime catalog page

2024-07-22 09:53 UTC, andrey-gazzaev requested changes
![image](https://github.com/user-attachments/assets/b6e61dad-e139-4928-850f-d399c3d47257)
It looks like the application's deploy is broken.

2024-07-22 09:53 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime-catalog/anime-catalog.component.css
> +  font-size: 32px;
Let's use the variable as you did in the first task

2024-07-22 09:53 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime-catalog/anime-catalog.component.ts
> +	selector: 'main-page',
Don't forget to add the application prefix to custom elements `camp`

2024-07-22 09:53 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime-table/anime-table.component.css
> +}
Let's use global styles to style native and material elements

2024-07-22 09:53 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime-table/anime-table.component.html
> +<table mat-table [dataSource]="animeData$" class="mat-elevation-z8">
Don't forget to add the trackby function to the table https://material.angular.io/cdk/table/overview#trackby

2024-07-22 09:53 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime-table/anime-table.component.ts
> +	TitleEng = 'English title',
Table column values ​​are used to generate table classes. Change the values ​​by removing spaces.
https://material.angular.io/components/table/overview#styling-columns

2024-07-22 09:53 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime-table/anime-table.component.ts
> +	public ngOnInit(): void {
To initialize the fields of a class you have a constructor. Don't use `onInit` as a constructor

2024-07-22 09:53 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime-table/anime-table.component.ts
> +	public constructor(private fetchAnimeService: FetchAnimeService) {}
```suggestion
  private readonly fetchAnimeService = inject(FetchAnimeService);
  
	public constructor() {}
```

Let's use inject to import services

2024-07-22 09:53 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime-table/anime-table.component.ts
> +	protected animeData$!: Observable<Anime[]>;
```suggestion
	protected animeList$!: Observable<Anime[]>;
```
Data is too abstract a word and carries absolutely no meaning. For you can use the word `list`

2024-07-22 09:53 UTC, andrey-gazzaev commented on apps/angular/src/core/services/anime.service.ts
> +export class FetchAnimeService {
Why is an entity called an action? Besides, doesn’t this service already do or will do only one action? 

Most often, an entity can do more things than just get a list of values.

2024-07-22 09:53 UTC, andrey-gazzaev commented on apps/angular/src/core/services/anime.service.ts
> +	/** 1. */
2.

2024-07-22 09:53 UTC, andrey-gazzaev commented on apps/angular/src/core/services/anime.service.ts
> +	private readonly rootUrl = 'https://api.camp-js.saritasa.rocks/api/v1/';
in `AppConfig` you already contain the base URL

2024-07-22 09:53 UTC, andrey-gazzaev commented on apps/angular/src/theme/variables.css
> +  --space-20: 80px;
```suggestion
  /* Space variables */
  --space-base: 4px;
  --space-5: calc(5 *  var(--space-base));
  --space-6: 24px;
  --space-8: 32px;
  --space-10: 40px;
  --space-20: 80px;
```

Calculating these values ​​will make it easier for you to maintain and scale the application.

2024-07-22 09:53 UTC, andrey-gazzaev commented on libs/core/dtos/aired.dto.ts
> +export type AiredDto = {
It seems that the interface structure is abstract enough to be described at all time intervals.

2024-07-22 09:53 UTC, andrey-gazzaev commented on libs/core/dtos/aired.dto.ts
> +	/** Start airing date in format 2024-07-22T02:40:54.873Z. */
```suggestion
	/** 
	* Start airing date in format.
	* @example `2024-07-22T02:40:54.873Z`. 
	*/
```

2024-07-22 09:53 UTC, andrey-gazzaev commented on libs/core/dtos/anime-list.dto.ts
> +export type AnimeListDto = {
What if you have a list of genres, will you create the same type for it?

2024-07-22 09:53 UTC, andrey-gazzaev commented on libs/core/dtos/anime-list.dto.ts
> +export type AnimeListDto = {
It looks like you already have an interface for describing lists. `PaginationDto<T>`

2024-07-22 09:53 UTC, andrey-gazzaev commented on libs/core/mappers/anime-status.mapper.ts
> +		const statusMap: { [key in DtoStatus]: ModelStatus } = {
Try using the `Record` utility

2024-07-22 09:53 UTC, andrey-gazzaev commented on libs/core/models/anime.ts
> +	public readonly image: string;
Is this the exact picture? Could this be a URL to it?

2024-07-22 09:53 UTC, andrey-gazzaev commented on libs/core/models/anime.ts
> +	public readonly titleEng: string;
Don't use abbreviations. Unless they are considered generally accepted, like `id`

2024-07-22 09:53 UTC, andrey-gazzaev commented on libs/core/utils/enums/statusEnums.ts
> +export enum DtoStatus {
There is no need to store models of different levels in one file, let's separate them

2024-07-22 09:53 UTC, andrey-gazzaev commented on package.json
>      "@angular-devkit/core": "18.0.6",
Looks like you haven't updated all Angular packages

2024-07-23 03:50 UTC, fongradnastya commented on apps/angular/src/app/features/anime-table/anime-table.component.css
> +}
Do you mean I need to just move them to theme/style.css? I did this, but I'm wondering if I should create my own theme for the angular material like in this tutorial? https://material.angular.io/guide/theming

2024-07-23 06:03 UTC, khoanguyen-saritasa requested changes
BTW, please check why your Angular app is broken on GitHub preview.

2024-07-23 06:03 UTC, khoanguyen-saritasa commented on apps/angular/src/app/features/anime-table/anime-table.component.ts
> +	protected animeList$!: Observable<Anime[]>;
You have already assigned `animeList$` value in the constructor, so you don't need non-nullable assertion anymore
```suggestion
	protected animeList$: Observable<Anime[]>;
```

2024-07-23 09:32 UTC, fongradnastya commented
The Angular app now appears correctly in the GitHub preview.

2024-07-24 05:16 UTC, khoanguyen-saritasa requested changes

2024-07-24 05:16 UTC, khoanguyen-saritasa commented on apps/angular/src/app/features/anime-catalog/anime-catalog.component.html
> +</main>
I see you put the `anime-catalog` and `anime-table` component in the same level in the folder structure. This should not be the case. `anime-table` is a component of `anime-catalog` right? And it not the feature or anything related with it. `anime-catalog` should be only one. Therefore, you should move `anime-table` inside  `anime-catalog`. You can add a folder called `components` to have a better readability.

2024-07-24 05:16 UTC, khoanguyen-saritasa commented on apps/angular/src/app/features/anime-table/anime-table.component.ts
> +}
I'm not sure why you're mixing the table naming conventions. Please choose one: `camelCase` or `PascalCase` for this enum. But in our company, we usually go with `camelCase`.

2024-07-24 05:16 UTC, khoanguyen-saritasa commented on apps/angular/src/app/features/anime-table/anime-table.component.html
> +		<th mat-header-cell *matHeaderCellDef>{{ animeColumns.Status }}</th>
Please add a readable name for the title of column, not the key,

2024-07-24 05:16 UTC, khoanguyen-saritasa commented on apps/angular/src/app/features/anime-table/anime-table.component.ts
> +	protected animeList$: Observable<Anime[]>;
```suggestion
	/** Stream containing anime data from the server. */
	protected readonly animeList$: Observable<Anime[]>;
```

2024-07-24 05:16 UTC, khoanguyen-saritasa commented on apps/angular/src/environments/environment.prod.ts
> +	baseUrl: 'https://api.camp-js.saritasa.rocks/api/v1/',
Why is `production: false` in the production file? It should be `true`, right?

2024-07-24 10:57 UTC, khoanguyen-saritasa approved these changes
Look nice!

2024-07-24 10:59 UTC, andrey-gazzaev commented on .github/lead-reviewers.yml
> -    - danilkukryakov
Why did you update this file?

2024-07-24 10:59 UTC, andrey-gazzaev commented on .vscode/settings.json
> +{
Different programmers may have different vscode settings. Let's add this file to `gitignore`

2024-07-24 10:59 UTC, andrey-gazzaev commented on apps/angular/src/app/app.routes.ts
> +		component: AnimeCatalogComponent,
```suggestion
		loadComponent: ...,
```
Since you are using standalone components, you can use lazy loading for them
https://ultimatecourses.com/blog/lazy-load-standalone-components-via-load-component

2024-07-24 10:59 UTC, andrey-gazzaev commented on apps/angular/src/app/features/anime-catalog/anime-catalog.component.css
> +@import "../../../theme/variables.css";
Usually variables and all global styles are included at the theme level

2024-07-24 10:59 UTC, andrey-gazzaev commented on apps/angular/src/core/services/anime.service.ts
> +				console.error(response);
This way you won't catch the error, try catchError

2024-07-24 10:59 UTC, andrey-gazzaev commented on apps/angular/src/core/services/anime.service.ts
> +				}
```suggestion
				return response.results.map(dto => AnimeMapper.fromDto(dto));
```
the response always includes the results

2024-07-24 10:59 UTC, andrey-gazzaev commented on apps/angular/src/core/services/anime.service.ts
> +		return result$.pipe(
```suggestion
		return this.http.get<PaginationDto<AnimeDto>>('anime/anime/').pipe(
```

2024-07-24 10:59 UTC, andrey-gazzaev commented on apps/angular/src/core/services/anime.service.ts
> +	public constructor(private http: HttpClient) {}
Les't use `inject`

2024-07-24 10:59 UTC, andrey-gazzaev commented on apps/angular/src/shared/components/header/header.component.html
> +			<img src="assets/anime-icon.png" height="60" alt="Anime Catalog App Logo">
```suggestion
			<img src="assets/anime-icon.png" height="60" alt="">
```

Alt can be left empty if it is a decorative image

2024-07-24 10:59 UTC, andrey-gazzaev commented on apps/angular/src/shared/pipes/empty.pipe.ts
> +		}
```suggestion
	public transform(
		value: number | string | null | undefined,
		placeholder = '\u2014',
	): string | number {
```

2024-07-24 10:59 UTC, andrey-gazzaev commented on apps/react/src/api/config.ts
> +/** 1. */
Docs

2024-07-24 10:59 UTC, andrey-gazzaev commented on apps/react/src/api/index.ts
> +/** 1. */
same

2024-07-24 10:59 UTC, andrey-gazzaev commented on apps/react/src/store/store.ts
> +/** 1. */
Please check all similar places and correct the documentation

2024-07-24 10:59 UTC, andrey-gazzaev commented on libs/core/dtos/anime.dto.ts
> +	/** Anime creation date in format 2024-07-16T06:21:11.171641Z. */
```suggestion
	/** 
	 * Anime creation date in format .
	 * @example '2024-07-16T06:21:11.171641Z'
	 */
```

Please use jsdoc tags where possible

2024-07-24 10:59 UTC, andrey-gazzaev commented on libs/core/dtos/time-interval.dto.ts
> +export type TimeIntervalDto = {
```suggestion
export type DateTimeIntervalDto = {
```
Still, you work not only with time but also with the date

2024-07-24 10:59 UTC, andrey-gazzaev commented on libs/core/dtos/time-interval.dto.ts
> +	 * Start time interval date in format.
```suggestion
	 * Start time interval date.
```

2024-07-24 10:59 UTC, andrey-gazzaev commented on libs/core/models/anime.ts
> +	public readonly startDate: string | null;
```suggestion
	public readonly startDate: Date | null;
```
It's much easier to work with a date type than with a string

2024-07-24 10:59 UTC, andrey-gazzaev commented on libs/core/models/immerable.ts
> +/** 1. */
docs

2024-07-24 14:11 UTC, fongradnastya commented on .github/lead-reviewers.yml
> -    - danilkukryakov
It's not me, it's Pavel Zadorin's commit. I think, we should leave this as it is

2024-07-25 02:53 UTC, fongradnastya commented on apps/angular/src/shared/pipes/empty.pipe.ts
> +		}
Eslint doesnt like when we set a default value. So, I had to do it differently.

2024-07-25 07:33 UTC, andrey-gazzaev approved these changes
Well done 🔥

2024-07-25 07:33 UTC, andrey-gazzaev commented on apps/angular/src/app/app.routes.ts
> +			import('../app/features/anime-catalog/anime-catalog.component').then(x => x.AnimeCatalogComponent),
```suggestion
			import('../app/features/anime-catalog/anime-catalog.component').then(с => с.AnimeCatalogComponent),
```

2024-07-25 07:33 UTC, andrey-gazzaev commented on apps/angular/src/core/services/anime.service.ts
> +				return EMPTY;
It's better not to suppress the error. Let's give other operators in the chain the opportunity to handle errors
```suggestion
				return throwError(() => error);
```

2024-07-25 07:33 UTC, andrey-gazzaev commented on apps/angular/src/core/services/anime.service.ts
> +			take(3),
First of all, why?
Secondly, this operator will still not work, since the get function only executes once. The same thing if you do `take(1)`.

2024-07-25 07:33 UTC, andrey-gazzaev commented on apps/angular/src/theme/variables.css
> +  --main-text: 16px;
In the previous task, you made a whole set of variables for the font. Why don't you take advantage of them?

2024-07-25 07:33 UTC, andrey-gazzaev commented on libs/core/models/immerable.ts
> + * A utility type that takes a type `T` and returns a new type with the `[immerable]` property omitted.
```suggestion
 * Omits `[immerable]` property.
```

2024-07-29 05:11 UTC, dbitkovski commented on apps/angular/src/theme/styles.css
> +table tr {
If you override material styles you have to use its selectors. I know that most likely if we have material table we won't use native solution but I guess we'd rather avoid unexpected issues with default tables :)

2024-07-29 05:11 UTC, dbitkovski commented on apps/angular/src/theme/styles.css
> +  color: var(--on-surface) !important;
Material often has bad API and it forces you to configure theme to change colors. But there are cases when you can avoid `!important` because css custom properties are used.
For example, `mat-toolbar` styles both `color` and `background-color` with them
![image](https://github.com/user-attachments/assets/f5c7b5f9-e9b6-4e1d-bb5b-f05f479c8423)
So you can do like this:
```
.mat-toolbar {
  --mat-toolbar-container-background-color: var(--surface-overlay)
  --mat-toolbar-container-text-color: var(--on-surface)
}
```

Honestly I don't know which is better. When you use `!important` you say "I don't care how it's implemented I just want to be it this color". No matter what material devs do with this element, `color` will always be what you want it to be. But often material reuse its values for other purposes, for example, ripple effect. So even if you change `color` property, some state (active, hover) or ripple might still use previous value.

I, personally, would modify custom props instead of using `!important` but in this case it's up to you

2024-07-29 07:45 UTC, dbitkovski approved these changes

2024-07-29 07:45 UTC, dbitkovski commented on apps/angular/src/core/services/anime.service.ts
> +			catchError((error: unknown): Observable<Anime[]> => throwError(() => error)),
I don't think we need to catch an error just to throw it :)
Let's remove this line.

2024-07-29 07:54 UTC, merged