Feature/jc 654 anime list management
saritasa-nest/camp-js-2024-anastasia-fongrad pull request #6
Opened 2024-07-26 04:18 UTC by fongradnastya

2024-07-26 05:34 UTC, shalomich requested changes

2024-07-26 05:34 UTC, shalomich commented on apps/angular/src/app/features/anime-catalog/anime-catalog.component.ts
> +			this.pageIndex = 0;
Resetting the index is duplicated, which is not good. Try to put repetitive code in methods.

2024-07-26 05:34 UTC, shalomich commented on apps/angular/src/app/features/anime-catalog/anime-catalog.component.ts
> +				return this.animeApiService.getPagination(
I think this is not the best name for the method. I would not specify the detail at all that the anime is patinated, but in extreme cases I would call `getPaginatedAnime`.
```suggestion
				return this.animeApiService.getAll(
```

2024-07-26 05:34 UTC, shalomich commented on apps/angular/src/app/features/anime-catalog/anime-catalog.component.ts
> +				this.pageIndex = offset / this.pageSize;
I don't like that you mix the logic of generating anime parameters with query parameters. Ideally, you should have a separate type for anime parameters, the object of which will be mapped to query params and back.

2024-07-26 05:34 UTC, shalomich commented on apps/angular/src/app/features/anime-catalog/anime-catalog.component.ts
> +		this.sortParameters = [];
I suggest initializing properties with default values when declaring, and not in the constructor

2024-07-26 05:34 UTC, shalomich commented on apps/angular/src/app/features/anime-catalog/anime-catalog.component.ts
> +			order = `-${parameter}`;
This logic is similar to the formation of sorting for the api. To do this, you need to have a DTO for anime parameters and do it in the mapper.

2024-07-26 05:34 UTC, shalomich commented on apps/angular/src/app/features/anime-catalog/anime-catalog.component.ts
> +			order = `-${parameter}`;
I suggest creating an enum for sort direction with values in descending and ascending order

2024-07-26 05:34 UTC, shalomich commented on apps/angular/src/app/features/anime-catalog/anime-catalog.component.html
> +					<button class="main__reset-button" mat-flat-button type="button" (click)="cancelSorting()">Cancel sorting</button>
It's strange that you have a separate button to cancel sorting. In theory, you should do this from the handler to change the sorting.

2024-07-26 05:34 UTC, shalomich commented on apps/angular/src/app/features/anime-catalog/anime-catalog.component.html
> +			<mat-paginator #paginator [length]="(paginationData)?.totalCount" [pageSize]="pageSize" [pageIndex]="pageIndex" [pageSizeOptions]="[5, 10, 25, 100]" (page)="onPageChange($event)" aria-label="Selec
Let's have constant in component for `pageSizeOptions`

2024-07-26 05:34 UTC, shalomich commented on apps/angular/src/app/features/anime-catalog/anime-catalog.component.html
> +					<mat-select [(value)]="selectedType" (valueChange)="onSelectType()">
Do you really need both` [(value)]` and `(valueChange)`? Can we just do with `onSelectType()`?

2024-07-26 05:34 UTC, shalomich commented on apps/angular/src/core/services/anime.service.ts
> +		}
Ideally create HttpParams from object

`const httpParams = new HttpParams({ fromObject: { ...parameters } });`

2024-07-26 05:34 UTC, shalomich commented on apps/angular/src/core/services/anime.service.ts
> +		const result$ = this.http.get<PaginationDto<AnimeDto>>('anime/anime/', { params });
Please put the formation of the api uri in a separate service

2024-07-26 05:34 UTC, shalomich commented on apps/angular/src/core/services/anime.service.ts
> +				if ('results' in response) {
I'm not sure we need this check.

2024-07-26 05:34 UTC, shalomich commented on libs/core/utils/enums/model-type.enum.ts
> +	Unknown = '\u2014',
Please don't do that

2024-07-26 05:48 UTC, shalomich commented
It seems that some of the comments have already been corrected in your other PR and it turns out that I did not check the current version. I ask you not to open several PRS in parallel anymore, but do everything in order - merged, after opened a new one. Thanks.

2024-07-29 05:48 UTC, fongradnastya commented on apps/angular/src/app/features/anime-catalog/anime-catalog.component.html
> +					<mat-select [(value)]="selectedType" (valueChange)="onSelectType()">
In this case we can't because [(value)] binds the value to the value change event. When I remove (), the events are not processed

2024-07-29 05:51 UTC, fongradnastya commented on apps/angular/src/app/features/anime-catalog/anime-catalog.component.html
> +					<button class="main__reset-button" mat-flat-button type="button" (click)="cancelSorting()">Cancel sorting</button>
I don't think Angular material's tables provide built-in methods to remove order from a table. At least I haven't found one

2024-07-29 16:07 UTC, shalomich requested changes

2024-07-29 16:07 UTC, shalomich commented on apps/angular/src/core/services/anime-query-parameters.ts
> +	public getPaginatedAnime(): Observable<Pagination<Anime>> {
Getting anime is not the responsibility of this service. This code should be in the component.

2024-07-29 16:07 UTC, shalomich commented on apps/angular/src/core/services/anime-query-parameters.ts
> +	private readonly defaultPageSize = 5;
Please use constants outside component.

```suggestion
const START_PAGE_INDEX = 0;
const DEFAULT_PAGE_SIZE = 5;

/** Works with anime query parameters. */
@Injectable({
	providedIn: 'root',
})
export class AnimeQueryParametersService {
```

2024-07-29 16:07 UTC, shalomich commented on apps/angular/src/core/services/anime-query-parameters.ts
> +	public navigate(animeQueryParameters: AnimeQueryParameters): void {
I'm glad you got my idea right. The only thing is, for the convenience of using the service, I would make this method private and reuse it in separate methods to change the parameters of pagination, sorting and filters

2024-07-30 09:36 UTC, fongradnastya commented on apps/angular/src/app/features/anime-catalog/anime-catalog.component.ts
> +			this.animeParameters = animeParameters;
Now I have this code in ngOnInit that works with reactive form values. I'm not sure if I can rewrite it using async pipes
```suggestion
			public ngOnInit(): void {
		this.routeSubscription = this.routeParameterService.getParsedQueryParameters().subscribe(animeParameters => {
			this.animeParameters = animeParameters;
			this.animeForm.patchValue({
				animeType: animeParameters.animeType ?? [],
				searchQuery: animeParameters.searchQuery,
			});
		});
		this.formTypeSubscription = this.animeForm.get('animeType')?.valueChanges.subscribe(value => {
			const animeType = value?.map(type => type as AnimeType) ?? [];
			if (JSON.stringify(animeType) !== JSON.stringify(this.animeParameters.animeType)) {
				this.routeParameterService.onSelectType(animeType);
			}
		});
		this.formSearchSubscription = this.animeForm.get('searchQuery')?.valueChanges.subscribe(value => {
			if (value !== this.animeParameters.searchQuery) {
				this.routeParameterService.onSearch(value ?? '');
			}
		});
	}
```

2024-07-30 09:39 UTC, fongradnastya commented on apps/angular/src/core/services/anime-query-parameters.ts
> +	public navigate(animeQueryParameters: AnimeQueryParameters): void {
I hope I understand correctly that I should move all methods that handle form changes to AnimeQueryParametersService? I did it this way now

2024-07-31 03:31 UTC, shalomich commented on apps/angular/src/core/services/anime-query-parameters.ts
> +		const limitPerPage = event.pageSize;
You shouldn't calculate offset here, it's not the responsibility of the service. In general, I'm not sure why we need offset, why not use PageIndex (pageNumber is better). According to the offset idea, we need to count in the mapper before sending the parameters to the backend. Also, you should not pass event, simpler arguments are better.

```suggestion
	public onPageChange(limitPerPage: number, pageNumber: number): void {
```

2024-07-31 03:31 UTC, shalomich commented on apps/angular/src/core/services/anime-query-parameters.ts
> +	protected animeParameters: AnimeQueryParameters = {
We do not need to store this state. Our only state should be `this.route.queryParams` that we are observing. To change `this.route.queryParams` based on the previous values, use `queryParamsHandling: 'merge'`

```
private changePagination(limitPerPage: number, pageNumber: number) {
   const params: Partial<AnimePageQueryParams> = { limitPerPage, pageNumber };
   changeParams(params);
}

private changeParams(params: Partial<AnimePageQueryParams>): void {
  this.router.navigate([], { queryParams: parameters, queryParamsHandling: 'merge' });
}
```

2024-07-31 03:31 UTC, shalomich commented on apps/angular/src/core/services/anime-query-parameters.ts
> +	public onSortChange(event: SortParameter): void {
Please don't use preffix `on` in services. Is is not handler
```suggestion
	public chageSort(sort: SortParameter): void {
```

2024-07-31 03:31 UTC, shalomich commented on apps/angular/src/app/features/anime-catalog/components/anime-table/anime-table.component.ts
> +	private sortSubscription?: Subscription;
Is it redudant?

2024-07-31 03:31 UTC, shalomich commented on apps/angular/src/app/features/anime-catalog/anime-catalog.component.ts
> +		});
Ideally, have a separate private method for subscribing. Instead of storing the `formSubscription` as a separate field, it is better to use `takeUntilDestroyed` https://v17.angular.io/api/core/rxjs-interop/takeUntilDestroyed . And it makes no sense for us to have a subscription to each input field, it is better to subscribe to the entire form and call both routeParameterService methods, although it is more expedient to combine these two methods into one.

```
private readonly destroyRef = inject(DestroyRef);

public ngOnInit(): void {
  this.subscribeToFormChange();
}

private subscribeToFormChange(): void {
   this.animeForm.valueChanges.pipe(
       takeUntilDestroyed(this.destroyRef),
   ).subscribe(formValue => this.routeParameterService.changeFilters(formValue))
} 
```

2024-07-31 12:55 UTC, gevorg-gevorgyan-saritasa commented on apps/angular/src/app/features/anime-catalog/components/anime-table/anime-table.component.ts
> +	public emitSortChange(event: Sort): void {
Basically, this method handles table sorting in the first place, so it would be more correct to name it as a handle method, like `onSortChange`

2024-08-06 03:14 UTC, shalomich requested changes
You are already close to success. It remains to push a little more.

2024-08-06 03:14 UTC, shalomich commented on apps/angular/src/app/features/anime-catalog/anime-catalog.component.ts
> +			if (isSearchChanged || isTypesChanged) {
Are you sure that without these conditions you will not be able to work normally?

2024-08-06 03:14 UTC, shalomich commented on apps/angular/src/app/features/anime-catalog/anime-catalog.component.ts
> +				this.animeForm.patchValue({
You do not need to subscribe to changes to the query parameters in order to change your form, because if you change them manually, the page will reload. Therefore, we only need to initialize the form with the current query parameters. To do this, you can add such a method to your `AnimeParametersService`.

```
/** Anime parameters. */
	public get animeParameters(): AnimeParameters {
		return this.parseAnimeParameters(this.activatedRoute.snapshot.queryParams);
	}
```

2024-08-06 03:14 UTC, shalomich commented on apps/angular/src/app/features/anime-catalog/anime-catalog.component.ts
> +	protected paginatedAnime$: Observable<Pagination<Anime>>;
```suggestion
	protected readonly paginatedAnime$: Observable<Pagination<Anime>>;
```

2024-08-06 03:14 UTC, shalomich commented on apps/angular/src/app/features/anime-catalog/anime-catalog.component.ts
> +	protected animeParameters: AnimeQueryParameters = {
I have already asked you to use `IObservable` for parameters and subscribe using `async` pipe

2024-08-06 12:01 UTC, timofei-maximov-saritasa commented on libs/core/mappers/pagination.mapper.ts
> +		});
What if you decide to use another entity, not just `Anime`? We can pass mapper here to make this pagination mapper reusable.

2024-08-07 03:03 UTC, shalomich approved these changes
You've done a great job. Well done!

2024-08-07 03:03 UTC, shalomich commented on apps/angular/src/app/features/anime-catalog/anime-catalog.component.html
> +			/>
Every use of `async` is to create a subscription. As a result, we have 7 subscriptions for two streams, which is not cool, we could do with two.

```suggestion
@if (animeParameters$ | async; as animeParameters) {
     @if (paginatedAnime$ | async; as paginatedAnime) {
          <camp-anime-filters
              [searchQuery]="animeParameters.searchQuery"
              [animeTypes]="animeParameters.animeTypes"
              (filtersChange)="routeParameterService.changeFilters($event.animeTypes, $event.searchQuery)"
              />
              <camp-anime-table
              [animeList]="paginatedAnime.results"
              [sorting]="animeParameters.animeSort"
              (sortChange)="routeParameterService.changeSortParameter($event)"
              />
              <mat-paginator
              [length]="paginatedAnime.totalCount"
              [pageSize]="animeParameters.limitPerPage"
              [pageIndex]="animeParameters.pageNumber"
              [pageSizeOptions]="pageSizeOptions"
              (page)="routeParameterService.changePagination($event.pageSize, $event.pageIndex)"
              aria-label="Select page"
              />
     }
}
			
```

2024-08-07 08:19 UTC, timofei-maximov-saritasa approved these changes

2024-08-07 09:16 UTC, dbitkovski approved these changes

2024-08-07 09:48 UTC, merged