Feature/jc 673 create user authorization
saritasa-nest/camp-js-2024-anastasia-fongrad pull request #7
Opened 2024-08-08 09:23 UTC by fongradnastya

Created a user authorization feature

2024-08-13 18:21 UTC, maxineo requested changes

2024-08-13 18:21 UTC, maxineo commented on apps/angular/src/core/services/form-validation.service.ts
> +	private clientErrorMessages: { [key: string]: string; } = {
```suggestion
	private clientErrorMessages: Readonly<Record<string, string>> = {
```

2024-08-13 18:21 UTC, maxineo commented on apps/angular/src/core/services/form-validation.service.ts
> +		if (!serverErrors) {
```suggestion
		if (serverErrors == null) {
```

2024-08-13 18:21 UTC, maxineo commented on apps/angular/src/core/services/form-validation.service.ts
> +		serverErrors: ServerError[] | null | void,
```suggestion
		serverErrors?: ServerError[] | null,
```

2024-08-13 18:21 UTC, maxineo commented on apps/angular/src/core/services/form-validation.service.ts
> +		serverErrors: ServerError[] | null | void,
```suggestion
		serverErrors?: ServerError[] | null,
```

2024-08-13 18:21 UTC, maxineo commented on apps/angular/src/core/services/form-validation.service.ts
> +		if (controlError) {
```suggestion
		if (controlError != null) {
```

2024-08-13 18:21 UTC, maxineo commented on apps/angular/src/core/services/form-validation.service.ts
> +			if (!control) {
```suggestion
			if (control == null) {
```

2024-08-13 18:21 UTC, maxineo commented on apps/angular/src/core/services/form-validation.service.ts
> +			if (existingErrors) {
```suggestion
			if (existingErrors != null) {
```

2024-08-13 18:21 UTC, maxineo commented on apps/angular/src/core/services/user-profile-api.service.ts
> +				if (!response.email) {
In `UserProfileDto` I see that `email` can only be a string, so Im not sure why you need that check.

2024-08-13 18:21 UTC, maxineo commented on apps/angular/src/core/services/user-profile-api.service.ts
> +					return;
You should be able to avoid widening type to `void` by using `filter` operator.

2024-08-13 18:21 UTC, maxineo commented on apps/angular/src/core/services/user-profile-api.service.ts
> +			catchError(() => of(undefined)),
Dont you think consumers can care about error?

2024-08-13 18:21 UTC, maxineo commented on libs/core/dtos/enums/error-message-dto.enum.ts
> +export enum ErrorMessageDto {
I dont think thats a good idea to keep all errors in a enum. There can be hundreds of different errors and you will have to keep them up to date for the mapping to work.

2024-08-13 18:21 UTC, maxineo commented on libs/core/mappers/authorization-token.mapper.ts
> +	 * @param dto Anime dto.
Wrong description.

2024-08-13 18:21 UTC, maxineo commented on apps/angular/src/app/features/registration/components/registration-form/registration-form.model.ts
> +			],
It looks like its not necessary to apply these validator for entire form. You can change validators to work with fields, and you will be able to apply them to individual fields.

2024-08-19 07:37 UTC, karbik-creator requested changes

2024-08-19 07:37 UTC, karbik-creator commented on apps/angular/src/app/features/login/components/login-form/login-form.component.html
> +		<button mat-raised-button color="primary" type="submit" [disabled]="!loginForm.valid">Login</button>
Disabling a button is bad practice. You can read about it here https://www.smashingmagazine.com/2021/08/frustrating-design-patterns-disabled-buttons/#the-downsides-of-disabled-buttons
So let's remove this attribute and add a validity check to submit method

2024-08-19 07:37 UTC, karbik-creator commented on apps/angular/src/app/features/login/components/login-form/login-form.component.ts
> +		if (!this.loginForm?.valid) {
```suggestion
		if (this.loginForm?.invalid) {
```

2024-08-19 07:37 UTC, karbik-creator commented on apps/angular/src/app/features/login/components/login-form/login-form.component.ts
> +	}
Let's instead of subscribing to each control, make one subscription to the form and use `updateValueAndValidity`
```suggestion
	private initializeErrorsReset(): void {
		this.loginForm.valueChanges.pipe(takeUntilDestroyed(this.destroyRef))
			.subscribe(() => this.loginForm.updateValueAndValidity());
	}
```

2024-08-19 07:37 UTC, karbik-creator commented on apps/angular/src/app/features/registration/components/registration-form/registration-form.component.html
> +				<input matInput id="password" type="password" formControlName="password">
```suggestion
				<input matInput type="password" formControlName="password">
```

2024-08-19 07:37 UTC, karbik-creator commented on apps/angular/src/app/features/registration/components/registration-form/registration-form.component.html
> +				<input matInput id="confirmPassword" type="password" formControlName="confirmPassword">
```suggestion
				<input matInput type="password" formControlName="confirmPassword">
```

2024-08-19 07:37 UTC, karbik-creator commented on apps/angular/src/core/services/authorization.service.ts
> +			}),
```suggestion
			map(accessToken => accessToken !== null)
```

2024-08-19 07:37 UTC, karbik-creator commented on apps/angular/src/app/features/registration/components/registration-form/registration-form.model.ts
> +		passwordControl.valueChanges.subscribe(() => {
don't forget to unsubscribe

2024-08-20 06:07 UTC, pavelzadorin-saritasa approved these changes

2024-08-20 06:33 UTC, karbik-creator requested changes

2024-08-20 06:33 UTC, karbik-creator commented on apps/angular/src/app/features/login/components/login-form/login-form.component.ts
> +			.subscribe();
Let's improve the readability of the code a little
```suggestion
		this.authService.login(formData).pipe(
			catchError((error: unknown) => {
				const errors = this.formValidationService.parseError(error);
				this.formValidationService.setFormErrors(this.loginForm, errors);
				this.changeDetectorRef.markForCheck();

				return EMPTY;
			}),
		)
			.subscribe(() => this.loginSuccess.emit());
```

2024-08-20 06:33 UTC, karbik-creator commented on apps/angular/src/app/features/login/components/login-form/login-form.component.ts
> +			.subscribe(() => this.loginForm.updateValueAndValidity());
I noticed an error in the console. Let's fix it and set a flag so that events aren't emitted
![image](https://github.com/user-attachments/assets/c2d08224-d5aa-4e47-83b5-30936d829ba3)

2024-08-20 12:36 UTC, karbik-creator commented on apps/angular/src/app/features/login/components/login-form/login-form.component.ts
> +					this.loginForm.updateValueAndValidity();
```suggestion
					this.loginForm.updateValueAndValidity({ emitEvent: false });
```

2024-08-20 12:37 UTC, karbik-creator commented on apps/angular/src/app/features/login/components/login-form/login-form.component.ts
> +					this.loginForm.updateValueAndValidity();
And we can remove `this.loginForm.dirty`

2024-08-20 12:41 UTC, karbik-creator commented on apps/angular/src/app/features/login/components/login-form/login-form.component.ts
> +			catchError((error: unknown) => this.formValidationService.parseError(error).pipe(
I think we can make the `parseError ` method return not a stream

2024-08-21 05:23 UTC, karbik-creator approved these changes

2024-08-22 06:20 UTC, dbitkovski approved these changes

2024-08-22 06:31 UTC, merged