Feature/jc 703 initialize react app
saritasa-nest/camp-js-2024-anastasia-fongrad pull request #9
Opened 2024-08-15 10:55 UTC by fongradnastya

Initialized a react app and created a basic page layout

2024-08-16 04:38 UTC, SofyaKirillova requested changes

2024-08-16 04:38 UTC, SofyaKirillova commented on apps/react/src/features/genres/components/GenreDetails/GenreDetails.module.css
> +  margin-left: -280px;
Why do you need such a large margin? Put the value in a separate variable

2024-08-16 04:38 UTC, SofyaKirillova commented on apps/react/src/features/genres/components/GenreDetails/GenreDetails.module.css
> +.mainOpen {
You aren't using this class

2024-08-16 04:38 UTC, SofyaKirillova commented on apps/react/src/features/genres/components/GenreFilters/GenreFilters.module.css
> +.inputBase {
Use BEM

2024-08-16 04:38 UTC, SofyaKirillova commented on apps/react/src/features/genres/components/GenreFilters/GenreFilters.module.css
> +  margin-left: 1rem;
We definitely need to use `rem` here, not `px`.

2024-08-16 04:38 UTC, SofyaKirillova commented on apps/react/src/features/genres/components/GenreFilters/GenreFilters.tsx
> +/** Memoized version of GenreFiltersComponent for performance optimization. */
```suggestion
/** Genre filters component. */
```

2024-08-16 04:38 UTC, SofyaKirillova commented on apps/react/src/features/genres/components/GenreFilters/GenreFilters.tsx
> +/** Filters for anime genres. */
No comments are needed here

2024-08-16 04:38 UTC, SofyaKirillova commented on apps/react/src/features/genres/components/GenreFilters/GenreFilters.tsx
> +				inputProps={{ 'aria-label': 'search google maps' }}
```suggestion
				placeholder='Search Genres ...'
				aria-label='search google maps'
```

2024-08-16 04:38 UTC, SofyaKirillova commented on apps/react/src/features/genres/components/GenreLayout/GenreLayout.module.css
> +  margin-left: calc(-1 * var(--sidebar-width));
Why is `-1` here?

2024-08-16 04:38 UTC, SofyaKirillova commented on apps/react/src/features/genres/components/GenreLayout/GenreLayout.module.css
> +  margin-left: 600px;
Why is there such a large margin here?

2024-08-16 04:38 UTC, SofyaKirillova commented on apps/react/src/features/genres/components/GenreLayout/GenreLayout.tsx
> +	}
Let's add a ternary operator below

2024-08-16 04:38 UTC, SofyaKirillova commented on apps/react/src/features/genres/components/GenreList/GenreList.tsx
> +	/** Click handler. */
Now it isn't clear from the comment what the function does

2024-08-16 04:38 UTC, SofyaKirillova commented on apps/react/src/features/genres/components/GenreList/GenreList.tsx
> +	readonly genres: Array<AnimeGenre>;
```suggestion
	readonly genres: readonly AnimeGenre[];
```

2024-08-16 04:38 UTC, SofyaKirillova commented on apps/react/src/features/genres/components/GenreList/GenreList.tsx
> +	const [selectedGenreId, setSelectedGenreId] = useState<number | undefined>(genreId ? +genreId : undefined);
```suggestion
	const [selectedGenreId, setSelectedGenreId] = useState<number | undefined>(genreId ? Number(genreId) : undefined);
```
https://wiki.saritasa.rocks/frontend/languages/ts-js/best-practices#dont-use-implicit-type-casting

2024-08-16 04:38 UTC, SofyaKirillova commented on apps/react/src/features/genres/pages/GenrePage/GenrePage.module.css
> +.drawerPaper {
This class isn't used

2024-08-16 04:38 UTC, SofyaKirillova commented on package.json
> +    "@fontsource/roboto": "^5.0.14",
It seems these libraries aren't being used

2024-08-16 09:59 UTC, SofyaKirillova approved these changes

2024-08-16 09:59 UTC, SofyaKirillova commented on apps/react/src/features/genres/components/GenreFilters/GenreFilters.module.css
>    padding: 2px 4px;
Please use variables

2024-08-16 09:59 UTC, SofyaKirillova commented on apps/react/src/features/genres/components/GenreList/GenreList.tsx
>  	onGenreClick: (id: number) => void;
```suggestion
	readonly onGenreClick: (id: number) => void;
```

2024-08-16 09:59 UTC, SofyaKirillova commented on apps/react/src/features/genres/components/GenreListItem/GenreListItem.tsx
>  	readonly onClick: () => void;
Now it is unclear by name what the function does

2024-08-16 09:59 UTC, SofyaKirillova commented on apps/react/src/features/genres/pages/GenrePage/GenrePage.tsx
> +];
Let's add a type

2024-08-16 09:59 UTC, SofyaKirillova commented on apps/react/src/features/genres/pages/GenrePage/GenrePage.tsx
> +	const open = useSelector(selectIsDrawerOpen);
```suggestion
	const drawerOpe = useSelector(selectIsDrawerOpen);
```

2024-08-16 09:59 UTC, SofyaKirillova commented on apps/react/src/features/genres/components/NavigationList/NavigationList.tsx
> +	items: {
```suggestion
	readonly items: readonly {
```

2024-08-16 10:13 UTC, timofei-maximov-saritasa commented on apps/react/src/features/genres/components/GenreFilters/GenreFilters.module.css
> +.inputBase {
@fongradnastya @SofyaKirillova We don't use BEM in react

2024-08-16 11:04 UTC, timofei-maximov-saritasa commented on apps/react/src/features/genres/components/GenreFilters/GenreFilters.module.css
> +.inputBase {
@fongradnastya If you changed it to BEM, leave it as-is but there is no point in BEM with CSS modules:
1. We use components(BEM existed before this concept, so it doesn't help us separate blocks)
2. It's easier to use camelCase in classNames - `className={styles.fooBar}` vs `className={styles['foo__bar']}`

2024-08-18 16:40 UTC, andrey-gazzaev commented on apps/react/src/features/genres/components/GenreLayout/GenreLayout.tsx
> +	const open = useSelector(selectIsDrawerOpen);
```suggestion
	const isDrawerOpen= useSelector(selectIsDrawerOpen);
```

2024-08-18 16:40 UTC, andrey-gazzaev commented on apps/react/src/features/genres/components/GenreLayout/GenreLayout.tsx
> +	};
Let's group the return statement at the bottom of the component

2024-08-18 16:40 UTC, andrey-gazzaev commented on apps/react/src/features/genres/components/GenreLayout/GenreLayout.tsx
> +	};
```
// states...

// hadlers...

// effects...

// some code...
  return <loading/>
//  some code...
  return <YourComponent/>

2024-08-18 16:40 UTC, andrey-gazzaev commented on apps/react/src/features/genres/components/GenreList/GenreList.tsx
> +	/** Handles displaying genre details on click. */
```suggestion
	/** Displaying genre details on click handler. */
```

2024-08-18 16:40 UTC, andrey-gazzaev commented on apps/react/src/features/genres/components/GenreList/GenreList.tsx
> +	};
Use useCallback. Systematic use of this hook will allow you to have a reduced number of rerenders

2024-08-18 16:40 UTC, andrey-gazzaev commented on apps/react/src/features/genres/components/NavigationList/NavigationList.tsx
> +type NavigationListProps = {
```suggestion
type Props = {
```
If you are not exporting a type, you can use the usual form of the name

2024-08-18 16:40 UTC, andrey-gazzaev commented on apps/react/src/features/genres/pages/GenrePage/GenrePage.tsx
> +	const iDrawerOpen = useSelector(selectIsDrawerOpen);
```suggestion
	const isDrawerOpen = useSelector(selectIsDrawerOpen);
```

2024-08-18 16:40 UTC, andrey-gazzaev commented on apps/react/src/features/genres/pages/GenrePage/GenrePage.tsx
> +			<MuiAppBar className={`${styles['main__app-bar']} ${iDrawerOpen ? styles['main__app-bar_open'] : ''}`}>
```suggestion
			<MuiAppBar className={clsx(styles['main__app-bar'], isDrawerOpen && styles['main__app-bar_open'] )}>
```

https://www.npmjs.com/package/clsx

2024-08-18 16:40 UTC, andrey-gazzaev commented on apps/react/src/features/genres/pages/GenrePage/GenrePage.tsx
> +			<MuiAppBar className={`${styles['main__app-bar']} ${iDrawerOpen ? styles['main__app-bar_open'] : ''}`}>
Try using this library. It will be easier to work with styles

2024-08-19 04:52 UTC, andrey-gazzaev approved these changes

2024-08-19 05:23 UTC, timofei-maximov-saritasa commented on apps/react/src/features/genres/components/GenreListItem/GenreListItem.tsx
> +		<ListItemButton
Let's use link component here over button.

`<ListItemButton component={NavLink} to={genreUrl}`

2024-08-19 05:23 UTC, timofei-maximov-saritasa commented on apps/react/src/features/genres/components/GenreList/GenreList.tsx
> +	}, [onGenreClick]);
You don't need it if you will handle navigation using links

2024-08-19 05:23 UTC, timofei-maximov-saritasa commented on apps/react/src/store/drawer/slice.ts
> +export default drawerSlice.reducer;
Do you need this?

2024-08-19 07:03 UTC, fongradnastya commented on apps/react/src/features/genres/components/GenreList/GenreList.tsx
> +	}, [onGenreClick]);
I started using navigation links but I still need a handler to set the selected genre

2024-08-19 07:26 UTC, dbitkovski approved these changes

2024-08-19 08:12 UTC, fongradnastya commented on apps/react/src/store/drawer/slice.ts
> +export default drawerSlice.reducer;
I think so, because I need to share the state of the drawer between different pages.

2024-08-19 08:15 UTC, merged